language: rust
sudo: false

os:
  - linux
  - osx

rust:
  - stable

script:
    - |
        rvm install 2.4.0 &&
        rvm use 2.4.0 &&
        gem install bundler &&
        bundle install &&
        bundle exec rake

notifications:
  email: false
