[package]
name = "lzf_fast"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.19"
lzf = "0.3.1"
ruru = { git = "https://github.com/d-unseductable/ruru" }

[profile.release]
lto = true
